export const PROFILE_ONBOARDING_EVENTS = {
  SHOWN: 'profile_onboarding_shown',
  COMPLETED: 'profile_onboarding_completed',
  SKIPPED: 'profile_onboarding_skipped',
  RETENTION_SHOWN: 'profile_onboarding_retention_shown',
  RETENTION_CONTINUED: 'profile_onboarding_retention_continued',
  RETENTION_COMPLETED: 'profile_onboarding_retention_completed',
  RETENTION_DEFER_ATTEMPT: 'profile_onboarding_retention_defer_attempt',
  RETENTION_DEFER_RESULT: 'profile_onboarding_retention_defer_result',
  RUNTIME_FAILED: 'profile_onboarding_runtime_failed',
  SETTINGS_SAVED: 'learner_profile_settings_saved',
  SETTINGS_CLEARED: 'learner_profile_settings_cleared',
  SETTINGS_RERUN_STARTED: 'learner_profile_settings_rerun_started',
  COLLECTION_ROUTE_CHOSEN: 'learner_profile_collection_route_chosen',
  ASSISTANT_ATTEMPT: 'learner_profile_assistant_attempt',
  ASSISTANT_RESULT: 'learner_profile_assistant_result',
} as const;
