#!/usr/bin/env bash
# Idempotent Cloud Agent install for AI-Shifu.
# Provisions native MySQL + Redis, the Python backend venv, and the cook-web
# frontend dependencies, then applies DB migrations and imports the demo course.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_DIR="${AI_SHIFU_VENV:-$HOME/.venvs/ai-shifu}"
API_ENV="$REPO_ROOT/src/api/.env"

echo "[install] repo root: $REPO_ROOT"

# 1) System packages: database, cache, media (pydub/ffmpeg) and build toolchain.
#    Install when ANY required package/command is missing so a partially
#    provisioned base image is repaired (not just when MySQL/Redis are absent).
need_packages=0
for cmd in mysqld redis-server ffmpeg curl gcc make pkg-config; do
  command -v "$cmd" >/dev/null 2>&1 || need_packages=1
done
dpkg -s python3.12-venv python3-dev build-essential >/dev/null 2>&1 || need_packages=1
if [ "$need_packages" = "1" ]; then
  echo "[install] installing system packages"
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update -y
  sudo apt-get install -y --no-install-recommends \
    mysql-server redis-server ffmpeg \
    python3.12-venv python3-dev build-essential pkg-config curl
fi

# 2) Start MySQL + Redis so migrations can run (safe to call repeatedly), then
#    block until both accept connections before any provisioning below.
bash "$REPO_ROOT/.cursor/start.sh"
bash "$REPO_ROOT/.cursor/wait-for-services.sh"

# 3) Per-environment credentials. Generated once and reused on re-runs by
#    reading them back from an existing .env, so the MySQL account password and
#    the connection string never drift apart.
gen_secret() { python3 -c 'import secrets; print(secrets.token_urlsafe(32))'; }
if [ -f "$API_ENV" ]; then
  # Reuse the existing credentials so the MySQL account and the connection
  # string never drift apart (.env is only (re)written when absent).
  DB_PASSWORD="$(sed -n 's|^SQLALCHEMY_DATABASE_URI="mysql://aishifu:\([^@]*\)@.*|\1|p' "$API_ENV" | head -n1)"
  SECRET_KEY="$(sed -nE 's/^SECRET_KEY="?([^"]*)"?$/\1/p' "$API_ENV" | head -n1)"
  if [ -z "$DB_PASSWORD" ]; then
    echo "[install] ERROR: could not read the DB password from existing $API_ENV;" >&2
    echo "[install]        refusing to reset it, which would desync MySQL from the" >&2
    echo "[install]        connection string. Fix or remove $API_ENV and re-run." >&2
    exit 1
  fi
  # A missing SECRET_KEY must be persisted now: the .env write below is skipped
  # when the file already exists, so an in-memory-only key would be lost.
  if [ -z "$SECRET_KEY" ]; then
    SECRET_KEY="$(gen_secret)"
    if grep -q '^SECRET_KEY=' "$API_ENV"; then
      sed -i "s|^SECRET_KEY=.*|SECRET_KEY=\"${SECRET_KEY}\"|" "$API_ENV"
    else
      printf '\nSECRET_KEY="%s"\n' "$SECRET_KEY" >> "$API_ENV"
    fi
  fi
else
  DB_PASSWORD="$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))')"
  SECRET_KEY="$(gen_secret)"
fi

# 4) Application database and local-only account (idempotent). The account is
#    scoped to localhost/127.0.0.1 and to the ai-shifu schema, with no GRANT
#    OPTION, and uses the per-environment password above.
sudo mysql <<SQL
CREATE DATABASE IF NOT EXISTS \`ai-shifu\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'aishifu'@'localhost' IDENTIFIED WITH caching_sha2_password BY '${DB_PASSWORD}';
CREATE USER IF NOT EXISTS 'aishifu'@'127.0.0.1' IDENTIFIED WITH caching_sha2_password BY '${DB_PASSWORD}';
ALTER USER 'aishifu'@'localhost' IDENTIFIED WITH caching_sha2_password BY '${DB_PASSWORD}';
ALTER USER 'aishifu'@'127.0.0.1' IDENTIFIED WITH caching_sha2_password BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`ai-shifu\`.* TO 'aishifu'@'localhost';
GRANT ALL PRIVILEGES ON \`ai-shifu\`.* TO 'aishifu'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL

# 5) Python virtualenv + backend dependencies.
if [ ! -x "$VENV_DIR/bin/python" ]; then
  python3 -m venv "$VENV_DIR"
fi
# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"
python -m pip install --upgrade "pip<25" setuptools wheel
pip install -r "$REPO_ROOT/src/api/requirements.txt"

# 6) Backend .env for local native services. Only created when missing so that
#    real secrets (e.g. a working LLM key) added later are preserved. Written
#    with 0600 permissions because it holds the DB password and signing key.
if [ ! -f "$API_ENV" ]; then
  echo "[install] writing $API_ENV"
  ( umask 177
    cat > "$API_ENV" <<ENV
# Local Cloud Agent development configuration (generated by .cursor/install.sh).
# Not for production. A real LLM key can be provided via an environment secret
# (OPENAI_API_KEY), which takes precedence over the placeholder below.
ENV="development"
MODE="api"
FLASK_APP="app.py"
SWAGGER_ENABLED="True"
SQLALCHEMY_DATABASE_URI="mysql://aishifu:${DB_PASSWORD}@127.0.0.1:3306/ai-shifu?charset=utf8mb4"
REDIS_HOST="127.0.0.1"
REDIS_PORT="6379"
SECRET_KEY="${SECRET_KEY}"
UNIVERSAL_VERIFICATION_CODE="1024"
CAPTCHA_CODE_OVERRIDE="0000"
LOGIN_METHODS_ENABLED="phone"
DEFAULT_LOGIN_METHOD="phone"
ADMIN_LOGIN_GRANT_CREATOR_WITH_DEMO="True"
OPENAI_API_KEY="PLACEHOLDER_SET_A_REAL_LLM_KEY_FOR_GENERATION"
SHARED_I18N_ROOT="$REPO_ROOT/src/i18n"
CELERY_BROKER_URL="redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND="redis://127.0.0.1:6379/1"
ENV
  )
fi
chmod 600 "$API_ENV"

# 7) Database schema + demo course. The demo import itself returns success when
#    only the optional AI "summary" step is skipped (no real LLM key); any other
#    failure is surfaced so a broken import fails the install.
cd "$REPO_ROOT/src/api"
export FLASK_APP=app.py
python scripts/repair_dev_migration_state.py
flask db upgrade
flask console update_demo_shifu

# 8) Frontend dependencies (exact, from lockfile).
cd "$REPO_ROOT/src/cook-web"
npm ci

echo "[install] done"
