"""Referral domain constants."""

from __future__ import annotations

REFERRAL_CAMPAIGN_STATUS_DRAFT = 7801
REFERRAL_CAMPAIGN_STATUS_ACTIVE = 7802
REFERRAL_CAMPAIGN_STATUS_PAUSED = 7803
REFERRAL_CAMPAIGN_STATUS_ENDED = 7804
REFERRAL_CAMPAIGN_STATUS_ARCHIVED = 7805

REFERRAL_RULE_STATUS_DRAFT = 7811
REFERRAL_RULE_STATUS_ACTIVE = 7812
REFERRAL_RULE_STATUS_PAUSED = 7813
REFERRAL_RULE_STATUS_ENDED = 7814

REFERRAL_INVITE_CODE_STATUS_ACTIVE = 7821
REFERRAL_INVITE_CODE_STATUS_DISABLED = 7822

REFERRAL_TRIGGER_INVITED_REGISTRATION = "invited_registration"

REFERRAL_REWARD_TARGET_INVITER = "inviter"
REFERRAL_REWARD_TARGET_INVITEE = "invitee"

REFERRAL_REWARD_TYPE_BILLING_PLAN_CYCLE = "billing_plan_cycle"

REFERRAL_INVITE_EVENT_LINK_CLICKED = "invite_link_clicked"
REFERRAL_INVITE_EVENT_REGISTRATION_PAGE_VIEWED = "registration_page_viewed"
REFERRAL_INVITE_EVENT_CODE_ENTERED = "invite_code_entered"
REFERRAL_INVITE_EVENT_REGISTRATION_SUBMITTED = "registration_submitted"

REFERRAL_INVITE_EVENT_TYPES = {
    REFERRAL_INVITE_EVENT_LINK_CLICKED,
    REFERRAL_INVITE_EVENT_REGISTRATION_PAGE_VIEWED,
    REFERRAL_INVITE_EVENT_CODE_ENTERED,
    REFERRAL_INVITE_EVENT_REGISTRATION_SUBMITTED,
}

REFERRAL_RELATION_STATUS_REGISTERED = 7831
REFERRAL_RELATION_STATUS_REWARD_GENERATED = 7832
REFERRAL_RELATION_STATUS_REWARD_PENDING_EFFECTIVE = 7833
REFERRAL_RELATION_STATUS_REWARD_ACTIVE = 7834
REFERRAL_RELATION_STATUS_REWARD_ENDED = 7835
REFERRAL_RELATION_STATUS_REWARD_SKIPPED_CAP = 7836
REFERRAL_RELATION_STATUS_ABNORMAL_REVIEWING = 7837
REFERRAL_RELATION_STATUS_CANCELED = 7838

REFERRAL_ABNORMAL_STATUS_NORMAL = 7841
REFERRAL_ABNORMAL_STATUS_REVIEWING = 7842
REFERRAL_ABNORMAL_STATUS_CONFIRMED_ABNORMAL = 7843

REFERRAL_REWARD_STATUS_GENERATED = 7851
REFERRAL_REWARD_STATUS_PENDING_EFFECTIVE = 7852
REFERRAL_REWARD_STATUS_ACTIVE = 7853
REFERRAL_REWARD_STATUS_EXPIRED = 7854
REFERRAL_REWARD_STATUS_FROZEN = 7855
REFERRAL_REWARD_STATUS_CANCELED = 7856
REFERRAL_REWARD_STATUS_SKIPPED_CAP = 7857

REFERRAL_REWARD_CAP_SCOPE_PER_INVITER = "per_inviter"
REFERRAL_REWARD_CAP_SCOPE_PER_CAMPAIGN = "per_campaign"
REFERRAL_REWARD_CAP_SCOPE_NONE = "none"

REFERRAL_INVITEE_BENEFIT_EXISTING_TRIAL_ONLY = "existing_trial_only"

REFERRAL_REWARD_TIMING_IMMEDIATE_EXTEND_OR_DEFER = "immediate_extend_or_defer"

REFERRAL_REWARD_GRANTED_STATUSES = {
    REFERRAL_REWARD_STATUS_GENERATED,
    REFERRAL_REWARD_STATUS_PENDING_EFFECTIVE,
    REFERRAL_REWARD_STATUS_ACTIVE,
    REFERRAL_REWARD_STATUS_EXPIRED,
}
